CREATE TABLE PERSONS (
id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
name VARCHAR(128) NOT NULL,
birthday VARCHAR(128));

CREATE TABLE MOVIES (
id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
title VARCHAR(128) NOT NULL,
movieYear INTEGER,
genre VARCHAR(128),
length INTEGER);

CREATE TABLE RELATIONSHIPS (
id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
movieId INTEGER NOT NULL,
personId INTEGER NOT NULL,
director BOOLEAN NOT NULL,
writer BOOLEAN NOT NULL,
movieCast BOOLEAN NOT NULL);